lizard

diff --git a/tests/linter b/tests/linter
--- a/tests/linter
+++ b/tests/linter
@@ -4,12 +4,19 @@ if ! [[ -d env ]]; then
 	python3 -mvenv env
 	source env/bin/activate
 
-	pip install pylint pyflakes mypy types-colorama types-psutil types-tensorflow
+	pip install pylint pyflakes mypy types-colorama types-psutil types-tensorflow lizard
 
 	pip install -r requirements.txt
 fi
 
 source env/bin/activate
+
+echo "===> lizard ===>"
+
+if ! lizard; then
+	echo "pylint asanai.py failed. Exiting."
+	exit 1
+fi
 
 echo "===> pylint ===>"
 
