added exit

diff --git a/tools/linter b/tools/linter
--- a/tools/linter
+++ b/tools/linter
@@ -4,19 +4,22 @@ if ! [[ -d env ]]; then
 	python3 -mvenv env
 	source env/bin/activate
 
-	pip install pylint flake8 pyflakes bandit deadcode
+	pip install pylint pyflakes
 
 	pip install -r requirements.txt
 fi
 
 source env/bin/activate
 
-pylint asanai.py
+if ! pylint asanai.py; then
+	echo "pylint asanai.py failed. Exiting."
+	exit 1
+fi
 
-pyflakes asanai.py
 
-#bandit asanai.py
+if ! pyflakes asanai.py; then
+	echo "pyflakes asanai.py failed. Exiting"
+	exit 2
+fi
 
-#deadcode asanai.py
-
-#flake8 asanai.py
+exit 0
